In [6]:
# day06 - ex02.ipynb에 이어서
import numpy as np
# 3. 기능
li1 = [1,2,3,4]
# 리스트의 기능은 데이터를 추가/수정/삭제하는 기본적인 기능이 주가 됨
li1.append(10)
# 내장 함수를 이용하여 통계를 구할 수 있으나 기능이 부족함
sum(li1)

arr1 = np.array(li1)
# 넘파이의 배열은 여러 수학적 기능을 제공
arr1.max()
arr1.min()
arr1.sum()
arr1.mean() # 평균
arr1.std() # 표준편차

np.float64(3.1622776601683795)

In [13]:
# 배열의 인덱싱과 슬라이싱
li = [x * 2 for x in range(1, 6)]
li

arr1 = np.array(li)
print(arr1)

# 기본인덱싱
print(arr1[0])

# 기본 슬라이싱
print(arr1[1:3])

# 인덱스 리스트 사용(fancy 인덱싱)
# 0, 2, 3번째 요소를 가져옴
arr1[[0, 2, 3]]

# 불리언 인덱싱(마스킹)
mask = [True, False, True, False, False]
print(arr1[mask])
# 활용
arr1 > 5

[ 2  4  6  8 10]
2
[4 6]


array([False, False,  True,  True,  True])

### 스칼라(Scalar)
- 하나의 값으로 표현되는 데이터
- numpy에서 스칼라는 0차원 배열로 표현함

### 넘파이의 데이터 타입
- 2^32, 2^64 범위의 숫자 표현할 수 있음
- 디폴트는 64
- 정수형 : int32, int64
- 실수형 : float32, float64
- 논리형 : bool

In [23]:
import numpy as np

# 스칼라 생성
scalar_int = np.array(5)
scalar_float = np.array(3.14)

# 스칼라의 특성
print(f"정수형 스칼라 : {scalar_int}")
print(f"차원 : {scalar_int.ndim}")
print(f"형태 : {scalar_int.shape}")
print(f"데이터 타입 : {scalar_int.dtype}")

# 스칼라는 일반적인 값처럼 사용하면 됨
a = np.array(7)
b = np.array(3)
print(a + b)
a - b
a * b
a / b

정수형 스칼라 : 5
차원 : 0
형태 : ()
데이터 타입 : int64
10


np.float64(2.3333333333333335)

In [29]:
base = 2 
exp = 3
print(f'밑 : {base}, 지수 : {exp}')
print(f'밑 ** 지수 : {base ** exp}')

# 수학 함수와 스칼라
x = np.array(16)
print(f'제곱근 : {np.sqrt(x)}')
print(f'자연지수: {np.exp(2)}')
print(f'이진로그 : {np.log2(16)}')
print(f'자연로그 : {np.log(16)}')

# 타입변환
float_scalar = np.array(5.7)
float_scalar.dtype

int_scalar = float_scalar.astype(int)
int_scalar
int_scalar.dtype

밑 : 2, 지수 : 3
밑 ** 지수 : 8
제곱근 : 4.0
자연지수: 7.38905609893065
이진로그 : 4.0
자연로그 : 2.772588722239781


dtype('int64')

### 벡터(Vector)
- 크기와 방향을 가진 데이터
- numpy에서는 1차원 배열로 표현
- [1,2,3]

### 특징
- 차원 : 1차원
- 형태 : (n, )
- 길이(size) : 벡터의 요소 개수

In [33]:
import numpy
# 벡터 생성
v1 = np.array([1,2,3,4,5])

# 특성 확인
v1.ndim
v1.shape
v1.size

# 벡터의 크기
np.linalg.norm(v1)

np.float64(7.416198487095663)

In [42]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# 수평 결합
h_stack = np.hstack([v1, v2])
h_stack

# 수직 결합
v_stack = np.vstack([v1, v2])
v_stack

# 벡터 분해
v = np.array([i for i in range(1, 7)])
split = np.split(v, 2)
split

# 내적
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a * b

result = np.dot(a, b)
result
a @ b

np.int64(32)

In [67]:
# 리스트는 언제든 데이터를 추가/삭제할 수 있음
li = [1, 2, 3, 7]
li.append(11)
li
li.pop(1)
li

# 리스트는 길이가 고정된 자료구조가 아니라 언제든 변경될 수 있는 자료구조(가변성)
# 넘파이의 배열은 크기가 고정된 배열임
# 즉 데이터 추가/삭제가 불가능(배열의 길이가 변경될 수 없음)

arr = np.array([1,2,3])
arr # arr은 영원히 3칸

# append(원본 배열, 추가할 데이터): 원본 배열과 추가할 데이터로  새로운 배열을 만들어 변환
arr2 = np.append(arr, [4,5,6])
arr2

# 데이터 수정
# 인덱싱 활용
arr = np.array([1,2,3])
arr[0] = 10
arr

arr = np.array([i for i in range(1, 11)])
# 범위를 단일 값으로 수정
arr[1:4] = 21
arr

# 범위에 데이터를 각각 수정
arr[1:3] = 11
arr

# 마스킹을 활용한 수정
arr = np.arange(100) # 0~99
arr

# 마스킹 적용
arr[arr > 50]

# 짝수만 선택
arr[arr % 2 == 0]
# 모든 짝수를 -1로 수정
arr[arr % 2 == 0] = -1
arr
# 변형
arr = np.arange(12)
print("원본 배열: ", arr)

# 2 * 6 배열로 변환
arr_2_6 = arr.reshape(2, 6)
print(arr_2_6)

arr_3_4 = arr.reshape(3,4)
print(arr_3_4)

# -1 사용한 자동 계산
arr_auto = arr.reshape(-1, 3)
arr_auto

원본 배열:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### 행렬(Matrix)
- 2차원으로 배열된 숫자들의 집합
- 행(row)과 열(column)으로 구성
- 표 형태의 데이터 구조

### 구성요소
- 행 : 가로 방향의 원소들
- 열 : 세로 방향의 원소들
- 원소(element) : 행렬의 각 데이터 항목
- 차원 : 2차원
- 형태 : (행의 수, 열의 수)

### 특수한 행렬
- 정방행렬 : 행과 열의 수가 같은 행렬
- 단위행렬 : 대각선이 1이고 나머지가 0인 정방행렬
- 대각행렬 : 대각선 외의 원소가 모두 0인 행렬
- 전치행렬 : 행과 열을 바꾼 행렬

In [73]:
# 행렬 생성
matrix1 = np.array([[1,2,3], [4,5,6]])
matrix1
matrix1.shape
matrix1.ndim

# 특수 행렬 생성
# 단위 행렬(대각선이 1인 정방행렬)
np.eye(3)
np.eye(5)

# 전치 행렬(행과 열을 바꿈)
matrix1
trans = matrix1.T
trans

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# 1. 행렬 연산
A = np.array([1,2], [3,4])
B = np.array([5,6], [7,8])
print(A)
print(B)

# 스칼라 곱(모든 원소에 스칼라값을 곱합)
A * 2

# 행렬 곱 (행렬 곱셈 규칙에 따라 계산)
A @ B

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [90]:
# 매트릭스 인덱싱과 슬라이싱
m1 = np.arange(1, 10).reshape(3,3)
print("m1\n", m1)

# 인덱싱
# 1. [행][열]
print(m1[0][1])
# 2. [행, 열]
print(m1[0, 1]) # 넘파이 배열에서 가능한 방법(리스트 불가능)

# 하나의 행 가져오기
print(m1[0]) # 행만 인덱싱

# 하나의 열 가져오기
print(m1[:, 1]) # 슬라이싱 활용
print(m1[:,2])

# 슬라이싱으로 범위 선택(붙어있는 범위)
print(m1[0:2, 0:2])
# [1~마지막 행, 1~마지막 열]
print(m1[1:, 1:])

# Fancy 인덱싱 (떨어져 있는 요소들 선택)
# [행, 열]
# [[0행, 2행], 모든 열]
m1[[0,2] ]

# [모든행, [0열, 2열]]
m1[:, [0,2]]
m1[[0,2], [1]]

# 조건 기반 인덱싱(마스킹)
m1[m1 > 5]


m1
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
2
2
[1 2 3]
[2 5 8]
[3 6 9]
[[1 2]
 [4 5]]
[[5 6]
 [8 9]]


array([6, 7, 8, 9])

In [96]:
# 매트릭스 데이터 추가/수정/삭제
# 추가/삭제 불가능

# 단일 요소 수정
m1[0,0] = 10
m1
m1[1]

# 행 전체 수정
m1[1] = 100
m1
m1[1] = [40, 50, 60]
m1

# 열 수정
# 모든 행 1열
m1[:, 1]
m1[:, 1] = [20, 50, 80]
m1

array([[10, 20,  3],
       [40, 50, 60],
       [ 7, 80,  9]])