## numpy(Numerical Python)
- 수치 계산을 위한 파이썬 라이브러리
- 데이터분석, 머신러닝에서 필수적으로 사용
- 배열이라는 자료구조를 제공하고 배열 연산을 위한 다양한 기능 제공
- 외부 라이브러리이기에 설치가 필요 -> pip install numpy

### numpy의 배열
1. ndarray(N-dimensional array)
    - 리스트와 유사하지만 더 강력한 기능 제공
    - 다차원 배열 객체

In [6]:
# 일반 리스트(1차원 리스트)
li = [1, 2, 3, 4, 5]

# 2차원 리스트(리스트 안에 리스트가 있는 형태)
li2 = [[1, 2], [3, 4], [5, 6]]
print(len(li2))
print(li2[0])
print(len(li2[0]))
print(li2[0][1])

li3 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(li3[0][2])

3
[1, 2]
2
2
3


주피터 노트북에서 넘파이 깔기(깃허브 코드스페이스임)

In [ ]:
%pip install numpy
%pip install --upgrade pip

In [9]:
import numpy as np

# 넘파이 배열 생성하기
# 1. array(): 리스트, 튜플 같은 객체를 이용한 배열 생성
arr = np.array([1, 2, 3, 4, 5])
arr
type(arr)

# 2. zeros(): 0으로 채워진 배열
# 0. = 0.0
np.zeros(5)  # 0이 5개 들어있는 배열 반환

# 3. ones(): 1로 채워진 배열
np.ones(10)

# 4. arange(): 범위 지정 배열(range와 유사), 실수 간격 단위 사용가능
np.arange(0, 10, 2)
np.arange(1, 2, 0.1)

# 5. linspace(): 균등 간격 배열
# 0 ~ 1까지 5등분
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
# 1. 2차원 리스트로 2차원 배열 생성
li = [[1, 2], [3, 4], [5, 6]]
np.array(li)

# 2. 튜플로 (행, 열) 설정
np.zeros((2, 3))
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
arr_zero = np.zeros(5)
arr_zero.shape # 배열의 모양(길이): (5, ) <- 1차원이라 길이
arr_zero.ndim # 차원 수 
arr_zero.dtype # 저장한 요소의 타입
arr_zero.size # 저장된 요소의 수

# 2차원 배열
arr_zero2 = np.zeros((5,3), dtype=int)
print(arr_zero2)

arr_zero2.shape
arr_zero2.ndim
arr_zero2.dtype
arr_zero2.size


[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


15

In [33]:
# 리스트와 배열의 차이
# 1. 데이터 타입
li = [1, "2", 3, "4"]
li  # 리스트는 다양한 타입의 값 저장 가능

arr = np.array([1, "2", 3, "4"])
arr  # 배열은 기본적으로 동일한 타입의 값들을 저장하는 것을 권장함
# arr은 모두 같은 타입으로 변경돼 있음

# 2. 연산
li1 = [1, 2, 3]
li2 = [4, 5, 6]
li1 + li2  # [1, 2, 3, 4, 5, 6]
li1 * 2  # [1, 2, 3, 1, 2, 3]

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr1 + arr2 # array([5, 7, 9])
arr1 * 3 # array([3, 6, 9])
arr2 **2 # array([16, 25, 36])


array([16, 25, 36])